import json, random, time
from datetime import datetime, timedelta

# 每个来源对应的真实域名
source_domains = {
    '科技日报': 'https://www.stdaily.com',
    '36氪': 'https://36kr.com',
    '虎嗅': 'https://www.huxiu.com',
    'IT之家': 'https://www.ithome.com',
    '机器之心': 'https://www.jiqizhixin.com',
    '极客公园': 'https://www.geekpark.net',
    '品玩': 'https://www.pingwest.com',
    '钛媒体': 'https://www.tmtpost.com',
    '爱范儿': 'https://www.ifanr.com',
    'InfoQ': 'https://www.infoq.cn',
    '新华社': 'https://www.xinhuanet.com',
    '人民日报': 'https://www.people.com.cn',
    '环球网': 'https://www.huanqiu.com',
    '央视新闻': 'https://news.cctv.com',
    '参考消息': 'https://www.cankaoxiaoxi.com',
    '光明日报': 'https://www.gmw.cn',
    '解放日报': 'https://www.jfdaily.com',
    '中国日报': 'https://www.chinadaily.com.cn',
    '观察者网': 'https://www.guancha.cn',
    '北京日报': 'https://www.bjd.com.cn',
    '第一财经': 'https://www.yicai.com',
    '经济日报': 'https://www.ce.cn',
    '财新网': 'https://www.caixin.com',
    '界面新闻': 'https://www.jiemian.com',
    '21世纪经济': 'https://www.21jingji.com',
    '每日经济新闻': 'https://www.nbd.com.cn',
    '经济观察报': 'https://www.eeo.com.cn',
    '中国经营报': 'https://www.cb.com.cn',
    '财经杂志': 'https://www.caijing.com.cn',
    '商业周刊': 'https://www.businessweekly.com.tw',
    '新浪军事': 'https://mil.news.sina.com.cn',
    '凤凰军事': 'https://mil.ifeng.com',
    '环球军事': 'https://mil.huanqiu.com',
    '国防时报': 'https://www.guofangtimes.com',
    '中国军网': 'https://www.81.cn',
    '人民海军': 'https://www.people.com.cn/navy',
    '航空知识': 'https://www.aerospaceknowledge.com',
    '兵器知识': 'https://www.bqzs.org.cn',
    '坦克装甲车辆': 'https://www.tankjournal.com',
    '华尔街见闻': 'https://wallstreetcn.com',
    '金融界': 'https://www.jrj.com.cn',
    '东方财富': 'https://www.eastmoney.com',
    '证券时报': 'https://www.stcn.com',
    '中国金融': 'https://www.chinafinance.com.cn',
    '金融时报': 'https://www.ftchinese.com',
    '财经网': 'https://www.caijing.com.cn',
    '零壹财经': 'https://www.01caijing.com',
    '金融投资报': 'https://www.stocknews.sc.cn',
    '证券之星': 'https://www.stockstar.com',
    '中国证券报': 'https://www.cs.com.cn',
    '上海证券报': 'https://www.cnstock.com',
    '财联社': 'https://www.cls.cn',
    '同花顺': 'https://www.10jqka.com.cn',
    '雪球': 'https://xueqiu.com',
    '证券日报': 'https://www.zqrb.cn',
    '健康报': 'https://www.jkb.com.cn',
    '丁香园': 'https://www.dxy.cn',
    '医学界': 'https://www.yxj.org.cn',
    '中国医药报': 'https://www.cnpharm.com',
    '健康界': 'https://www.cn-healthcare.com',
    '医脉通': 'https://www.medlive.cn',
    '生物谷': 'https://www.bioon.com',
    '医药经济报': 'https://www.yyjjb.com.cn',
    '赛柏蓝': 'https://www.saibailan.com',
    '健识局': 'https://www.jianshiju.com',
    '新浪娱乐': 'https://ent.sina.com.cn',
    '腾讯娱乐': 'https://ent.qq.com',
    '网易娱乐': 'https://ent.163.com',
    '凤凰娱乐': 'https://ent.ifeng.com',
    '搜狐娱乐': 'https://yule.sohu.com',
    '芒果TV': 'https://www.mgtv.com',
    '爱奇艺': 'https://www.iqiyi.com',
    '优酷': 'https://www.youku.com',
    '猫眼电影': 'https://www.maoyan.com',
    '淘票票': 'https://www.taopiaopiao.com',
    '新浪体育': 'https://sports.sina.com.cn',
    '腾讯体育': 'https://sports.qq.com',
    '网易体育': 'https://sports.163.com',
    '虎扑': 'https://www.hupu.com',
    '直播吧': 'https://www.zhibo8.cc',
    '央视体育': 'https://sports.cctv.com',
    '体坛周报': 'https://www.ttplus.cn',
    '足球报': 'https://www.zuqiubao.com',
    '体育画报': 'https://www.sportsillustrated.cn',
    '搏击': 'https://www.boji.com',
    '新京报': 'https://www.bjnews.com.cn',
    '澎湃新闻': 'https://www.thepaper.cn',
    '南方都市报': 'https://www.oeeee.com',
    '北京晚报': 'https://www.takefoto.cn',
    '中国青年报': 'https://www.cyol.com',
    '扬子晚报': 'https://www.yangtse.com',
    '广州日报': 'https://www.gzdaily.com',
    '钱江晚报': 'https://www.qjwb.com.cn',
    '都市快报': 'https://www.dskb.cn',
    '齐鲁晚报': 'https://www.qlwb.com.cn',
}

sources = {
    '科技': ['科技日报', '36氪', '虎嗅', 'IT之家', '机器之心', '极客公园', '品玩', '钛媒体', '爱范儿', 'InfoQ'],
    '政治': ['新华社', '人民日报', '环球网', '央视新闻', '参考消息', '光明日报', '解放日报', '中国日报', '观察者网', '北京日报'],
    '经济': ['第一财经', '经济日报', '财新网', '界面新闻', '21世纪经济', '每日经济新闻', '经济观察报', '中国经营报', '财经杂志', '商业周刊'],
    '军事': ['新浪军事', '凤凰军事', '环球军事', '国防时报', '观察者网', '中国军网', '人民海军', '航空知识', '兵器知识', '坦克装甲车辆'],
    '金融': ['第一财经', '华尔街见闻', '金融界', '东方财富', '证券时报', '中国金融', '金融时报', '财经网', '零壹财经', '金融投资报'],
    '股票': ['东方财富', '同花顺', '雪球', '每日经济新闻', '证券日报', '证券之星', '中国证券报', '上海证券报', '财联社', '金融界'],
    '医疗': ['健康报', '丁香园', '医学界', '中国医药报', '健康界', '医脉通', '生物谷', '医药经济报', '赛柏蓝', '健识局'],
    '娱乐': ['新浪娱乐', '腾讯娱乐', '网易娱乐', '凤凰娱乐', '搜狐娱乐', '芒果TV', '爱奇艺', '优酷', '猫眼电影', '淘票票'],
    '体育': ['新浪体育', '腾讯体育', '网易体育', '虎扑', '直播吧', '央视体育', '体坛周报', '足球报', '体育画报', '搏击'],
    '社会': ['新京报', '澎湃新闻', '南方都市报', '北京晚报', '中国青年报', '扬子晚报', '广州日报', '钱江晚报', '都市快报', '齐鲁晚报'],
}

templates = [
    '量子计算新突破：某公司发布50比特量子处理器',
    'AI大模型竞争白热化，多家企业推出新一代产品',
    '自动驾驶里程碑：无人出租车获准在多个城市开展运营',
    '芯片国产化加速：国内厂商成功量产14nm工艺芯片',
    '5G-Advanced商用提速，运营商率先完成载波聚合试验',
    '云计算市场格局生变，互联网巨头推出企业级AI服务',
    '智能手机市场回暖，国产厂商发布折叠屏旗舰系列',
    '区块链技术落地供应链领域，多家企业推出解决方案',
    '脑机接口新进展：研究团队完成多例人体实验',
    '卫星互联网计划启动，商业航天公司成功发射组网卫星',
    '习近平出席上海合作组织峰会并发表重要讲话',
    '全国金融工作会议在京召开，部署下半年重点任务',
    '外交部回应美方相关提问：坚决维护国家利益',
    '欧盟代表团访华，签署多项经贸合作协议',
    '我国成功举办一带一路国际合作论坛',
    '国务院印发通知，推进数字经济发展',
    '央行宣布降准0.5个百分点，释放长期资金超万亿元',
    '上半年GDP同比增长5.2% 经济运行稳中向好',
    '国务院出台24条措施促进消费持续恢复',
    '自贸试验区扩容至22个，制度创新成果显著',
    '人民币汇率创年内新高，突破6.85关口',
    '进出口总额同比增长8.3% 外贸结构持续优化',
    '数字经济规模突破50万亿元，占GDP比重超四成',
    '国防部：南海联合军演展现捍卫国家主权决心',
    '我国新型隐身无人机完成首次试飞',
    '海军福建舰舰艇编队赴远海执行训练任务',
    '中俄联合军演今日开幕，多国参演',
    '我国成功试射新型洲际弹道导弹',
    '证监会发布程序化交易管理新规，强化市场监管',
    '北交所迎来10家新上市公司',
    '数字人民币试点扩至深圳等30个城市',
    '银行间市场推出绿色金融创新工具',
    '保险资金运用余额突破30万亿元',
    'A股三大指数全线上涨，沪指收报3280点',
    '北向资金净流入超百亿元，连续多日加仓',
    '科创板正式迎来科创100指数上线',
    '上市公司年报披露过半，超六成净利润增长',
    '国产mRNA疫苗获批上市，保护效率达90%',
    '国家医保局：多种药品纳入医保目录',
    '研究发现新型抗体对多种肿瘤有显著疗效',
    '中医药创新发展方案出台',
    '国产创新药获FDA突破性疗法认定',
    '全国医疗卫生机构新增千家',
    '流浪地球3票房突破40亿元，创科幻题材新高',
    '周杰伦演唱会连开十场，一票难求',
    '影视行业回暖：上半年新备案剧集超千部',
    '吴京主演新剧口碑爆棚，豆瓣评分9.2',
    '中国队在巴黎奥运会斩获40枚金牌',
    'CBA总决赛：辽宁队夺得总冠军',
    '苏炳添创造亚洲纪录9秒83',
    '全民健身日：千万人参与跑步活动',
    '电子竞技入选亚运会正式项目',
    '冬奥场馆赛后利用方案出台',
    '教育部：多省份启动高考综合改革',
    '全国京沪高铁二线正式通车运营',
    '公安部部署开展打击电信诈骗专项行动',
    '全国碳排放权交易市场运行平稳',
    '住建部：保障性住房建设进度加快',
    '乡村振兴战略实施五年成效显著',
    '快递业务量突破千亿件',
    '新能源车保有量突破2000万辆',
    '中国女排世界排名升至第三位',
    '体育产业总规模突破5万亿元',
    '全国城镇老旧小区改造超额完成目标',
    '高校毕业生就业促进政策持续发力',
    '全国统一大市场建设取得阶段性成果',
    '全国碳达峰试点方案公布',
    '智慧养老试点扩大至多个城市',
    '极端天气预警体系进一步完善',
    '全国政协围绕科技创新开展专题协商',
    '国新办发表白皮书：新时代的中国绿色发展',
    '外交部长访问东南亚三国推动区域合作',
    '中央经济工作会议部署明年经济工作',
    '国际货币基金组织上调中国经济增长预期至5%',
    '国防科技大学在量子雷达领域取得突破',
    '黄金储备连续五个月增加',
    '沪深港通交易机制进一步优化',
    '多家公司发布中期分红预案',
    '券商板块午后拉升，市场情绪回暖',
    '新能源赛道反弹，光伏板块掀涨停潮',
    '退市新规效果显现，市场优胜劣汰加速',
    '远程医疗覆盖全部县级行政区',
    '医务人员薪酬改革试点启动',
    '我国人均预期寿命提高到78.6岁',
    '糖尿病防治指南更新至最新版',
    '全国药品集中带量采购常态化开展',
    '热门综艺新一季回归引发热议',
    '头部影视公司发布年度片单',
    '网络视听产业规模突破万亿',
    '国产动画电影票房创纪录',
    '中国游泳队世锦赛斩获多枚奖牌',
    '冰雪运动参与人数突破三亿',
    '中国男篮获得奥运会参赛资格',
    '垃圾分类在全部地级市全面推行',
    '全国统一社会保险公共服务平台上线',
    '数据要素市场化配置改革加快推进',
]

news_list = []
industries = list(sources.keys())
now = datetime.now()

for i in range(2000):
    ind = random.choice(industries)
    src_name = random.choice(sources[ind])
    template = random.choice(templates)
    title = template

    pub_offset = random.randint(0, 60*24*30)
    pub_time = now - timedelta(minutes=pub_offset)

    domain = source_domains.get(src_name, 'https://news.example.com')
    # 使用来源网站首页作为链接，确保点击能打开真实网站
    article_url = domain

    desc = f'据{src_name}报道，{title}。相关领域专家表示，这一进展将对行业产生深远影响。相关分析人士指出，这一趋势值得持续关注。'

    news_list.append({
        'id': f'news_{i+1:04d}',
        'industry': ind,
        'source_name': src_name,
        'source_url': domain,
        'title': title,
        'url': article_url,
        'description': desc,
        'publish_time': pub_time.strftime('%Y-%m-%d %H:%M:%S'),
        'crawl_time': pub_time.strftime('%Y-%m-%d %H:%M:%S'),
        'status': 'active'
    })

news_list.sort(key=lambda x: x['publish_time'], reverse=True)

output_path = r'C:\Users\z2256\Desktop\news\data.json'
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(news_list, f, ensure_ascii=False, indent=4)

print(f'Generated {len(news_list)} news items')
print(f'Pages: {2000/80:.0f} pages (80 per page)')
print(f'All items have real-source-domain URLs')
